name: Doxygen

# Controls when the action will run.
on:
  push:
    branches:  'master'

env:
  OGRE_VERSION: "latest"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Doxygen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build Doxygen
        working-directory: ./
        run: ./Scripts/BuildScripts/build_ci_doxygen.sh

      - name: Publish # Only on master branch
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
