name: Doxygen

# Controls when the action will run.
on:
  push:
    branches:  'master'

env:
  OGRE_VERSION: "latest"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Doxygen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Doxygen
        working-directory: ./
        run: ./Scripts/BuildScripts/build_ci_doxygen_step0.sh
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
      - name: Publish Doxygen
        working-directory: ./
        run: ./Scripts/BuildScripts/build_ci_doxygen_step1.sh
